<?php

namespace AppBundle\Repository;

/**
 * CallTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallTicketRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the total duration for a specified date
     *
     * @param $date
     * @return array
     */
    public function getTotalRealDuration($date)
    {
        $queryBuilder = $this->createQueryBuilder('c')
                            ->addSelect('SUM(c.durationReal) as realDuration')
                            ->where('DATE(c.date) >= :date')
                            ->setParameter('date', $date);

        return $queryBuilder->getQuery()->getScalarResult();
    }

    /**
     * Count number of sms
     *
     * @return mixed
     */
    public function countSms()
    {
        $queryBuilder = $this->createQueryBuilder('c')
          ->addSelect('COUNT(c.id) as smsCount')
          ->groupBy('c.subscriberNumber');

        return $queryBuilder->getQuery()->getScalarResult();
    }

    /**
     * Get the top 10 data within a time range
     *
     * @param $startTime
     * @param $endTime
     * @return array
     */
    public function getTopTen($startTime, $endTime)
    {
        $sql = 'SELECT * FROM call_ticket '
             . 'WHERE '
             . '(time < "'.$startTime.'" OR time > "'.$endTime.'") '
             . 'ORDER BY durationInvoiced DESC LIMIT 10';

        return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();
    }
}
